// Code generated by gobind. DO NOT EDIT.

// Java class irmagobridge.IrmaMobileBridge is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/privacybydesign/irmamobile/irmagobridge
package irmagobridge;

import go.Seq;

/**
 * IrmaMobileBridge is the iOS or Android native component that is used for message passing
 */
public interface IrmaMobileBridge {
	public void debugLog(String message);
	public void dispatchFromGo(String name, String payload);
	
}

