// Code generated by gobind. DO NOT EDIT.

// Java class irmagobridge.Irmagobridge is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/privacybydesign/irmamobile/irmagobridge
package irmagobridge;

import go.Seq;

public abstract class Irmagobridge {
	static {
		Seq.touch(); // for loading the native library
		_init();
	}
	
	private Irmagobridge() {} // uninstantiable
	
	// touch is called from other bound packages to initialize this package
	public static void touch() {}
	
	private static native void _init();
	
	private static final class proxyIrmaMobileBridge implements Seq.Proxy, IrmaMobileBridge {
		private final int refnum;
		
		@Override public final int incRefnum() {
		      Seq.incGoRef(refnum, this);
		      return refnum;
		}
		
		proxyIrmaMobileBridge(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
		
		public native void debugLog(String message);
		public native void dispatchFromGo(String name, String payload);
	}
	private static final class proxySigner implements Seq.Proxy, Signer {
		private final int refnum;
		
		@Override public final int incRefnum() {
		      Seq.incGoRef(refnum, this);
		      return refnum;
		}
		
		proxySigner(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
		
		public native byte[] publicKey(String keyname) throws Exception;
		public native byte[] sign(String keyname, byte[] msg) throws Exception;
	}
	
	
	/**
	 * DispatchFromNative receives events from the Android / iOS native side
	 */
	public static native void dispatchFromNative(String eventName, String payloadString);
	/**
	 * Prestart is invoked only on Android in MainActivity&#39;s onCreate, to initialize
	the Go binding at the earliest moment, instead of inside the Flutter plugin
	 */
	public static native void prestart();
	/**
	 * Start is invoked from the native side, when the app starts
	 */
	public static native void start(IrmaMobileBridge givenBridge, String appDataPath, String assetsPath, Signer signer, byte[] aesKey);
	public static native void stop();
}
