// Code generated by gobind. DO NOT EDIT.

// Java class irmagobridge.WrappedConfiguration is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/privacybydesign/irmamobile/irmagobridge
package irmagobridge;

import go.Seq;

/**
 * needed to inject logo into issuers
 */
public final class WrappedConfiguration implements Seq.Proxy {
	static { Irmagobridge.touch(); }
	
	private final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	WrappedConfiguration(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public WrappedConfiguration() { this.refnum = __New(); Seq.trackGoRef(refnum, this); }
	
	private static native int __New();
	
	// skipped field WrappedConfiguration.SchemeManagers with unsupported type: map[github.com/AVecsi/pq-irmago.SchemeManagerIdentifier]*github.com/AVecsi/pq-irmago.SchemeManager
	
	// skipped field WrappedConfiguration.Issuers with unsupported type: map[github.com/AVecsi/pq-irmago.IssuerIdentifier]*github.com/AVecsi/pq-irmago.Issuer
	
	// skipped field WrappedConfiguration.CredentialTypes with unsupported type: map[github.com/AVecsi/pq-irmago.CredentialTypeIdentifier]*github.com/AVecsi/pq-irmago.CredentialType
	
	// skipped field WrappedConfiguration.AttributeTypes with unsupported type: map[github.com/AVecsi/pq-irmago.AttributeTypeIdentifier]*github.com/AVecsi/pq-irmago.AttributeType
	
	// skipped field WrappedConfiguration.RequestorSchemes with unsupported type: map[github.com/AVecsi/pq-irmago.RequestorSchemeIdentifier]*github.com/AVecsi/pq-irmago.RequestorScheme
	
	// skipped field WrappedConfiguration.Requestors with unsupported type: map[string]*github.com/AVecsi/pq-irmago.RequestorInfo
	
	// skipped field WrappedConfiguration.IssueWizards with unsupported type: map[github.com/AVecsi/pq-irmago.IssueWizardIdentifier]*github.com/AVecsi/pq-irmago.IssueWizard
	
	// skipped field WrappedConfiguration.DisabledRequestorSchemes with unsupported type: map[github.com/AVecsi/pq-irmago.RequestorSchemeIdentifier]*github.com/AVecsi/pq-irmago.SchemeManagerError
	
	// skipped field WrappedConfiguration.DisabledSchemeManagers with unsupported type: map[github.com/AVecsi/pq-irmago.SchemeManagerIdentifier]*github.com/AVecsi/pq-irmago.SchemeManagerError
	
	// skipped field WrappedConfiguration.UpdateListeners with unsupported type: []github.com/AVecsi/pq-irmago.ConfigurationListener
	
	public final native String getPath();
	public final native void setPath(String v);
	
	// skipped field WrappedConfiguration.PrivateKeys with unsupported type: github.com/AVecsi/pq-irmago.PrivateKeyRing
	
	// skipped field WrappedConfiguration.Scheduler with unsupported type: *github.com/go-co-op/gocron.Scheduler
	
	// skipped field WrappedConfiguration.Warnings with unsupported type: []string
	
	public native byte[] marshalJSON() throws Exception;
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof WrappedConfiguration)) {
		    return false;
		}
		WrappedConfiguration that = (WrappedConfiguration)o;
		// skipped field WrappedConfiguration.SchemeManagers with unsupported type: map[github.com/AVecsi/pq-irmago.SchemeManagerIdentifier]*github.com/AVecsi/pq-irmago.SchemeManager
		
		// skipped field WrappedConfiguration.Issuers with unsupported type: map[github.com/AVecsi/pq-irmago.IssuerIdentifier]*github.com/AVecsi/pq-irmago.Issuer
		
		// skipped field WrappedConfiguration.CredentialTypes with unsupported type: map[github.com/AVecsi/pq-irmago.CredentialTypeIdentifier]*github.com/AVecsi/pq-irmago.CredentialType
		
		// skipped field WrappedConfiguration.AttributeTypes with unsupported type: map[github.com/AVecsi/pq-irmago.AttributeTypeIdentifier]*github.com/AVecsi/pq-irmago.AttributeType
		
		// skipped field WrappedConfiguration.RequestorSchemes with unsupported type: map[github.com/AVecsi/pq-irmago.RequestorSchemeIdentifier]*github.com/AVecsi/pq-irmago.RequestorScheme
		
		// skipped field WrappedConfiguration.Requestors with unsupported type: map[string]*github.com/AVecsi/pq-irmago.RequestorInfo
		
		// skipped field WrappedConfiguration.IssueWizards with unsupported type: map[github.com/AVecsi/pq-irmago.IssueWizardIdentifier]*github.com/AVecsi/pq-irmago.IssueWizard
		
		// skipped field WrappedConfiguration.DisabledRequestorSchemes with unsupported type: map[github.com/AVecsi/pq-irmago.RequestorSchemeIdentifier]*github.com/AVecsi/pq-irmago.SchemeManagerError
		
		// skipped field WrappedConfiguration.DisabledSchemeManagers with unsupported type: map[github.com/AVecsi/pq-irmago.SchemeManagerIdentifier]*github.com/AVecsi/pq-irmago.SchemeManagerError
		
		// skipped field WrappedConfiguration.UpdateListeners with unsupported type: []github.com/AVecsi/pq-irmago.ConfigurationListener
		
		String thisPath = getPath();
		String thatPath = that.getPath();
		if (thisPath == null) {
			if (thatPath != null) {
			    return false;
			}
		} else if (!thisPath.equals(thatPath)) {
		    return false;
		}
		// skipped field WrappedConfiguration.PrivateKeys with unsupported type: github.com/AVecsi/pq-irmago.PrivateKeyRing
		
		// skipped field WrappedConfiguration.Scheduler with unsupported type: *github.com/go-co-op/gocron.Scheduler
		
		// skipped field WrappedConfiguration.Warnings with unsupported type: []string
		
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {getPath()});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("WrappedConfiguration").append("{");
		b.append("Path:").append(getPath()).append(",");
		return b.append("}").toString();
	}
}

