// Code generated by gobind. DO NOT EDIT.

// Java class irmagobridge.WrappedCredentialType is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/privacybydesign/irmamobile/irmagobridge
package irmagobridge;

import go.Seq;

public final class WrappedCredentialType implements Seq.Proxy {
	static { Irmagobridge.touch(); }
	
	private final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	WrappedCredentialType(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public WrappedCredentialType() { this.refnum = __New(); Seq.trackGoRef(refnum, this); }
	
	private static native int __New();
	
	public final native String getLogo();
	public final native void setLogo(String v);
	
	// skipped field WrappedCredentialType.CredentialType with unsupported type: github.com/AVecsi/pq-irmago.CredentialType
	
	// skipped method WrappedCredentialType.AttributeType with unsupported parameter or return types
	
	// skipped method WrappedCredentialType.ContainsAttribute with unsupported parameter or return types
	
	// skipped method WrappedCredentialType.Identifier with unsupported parameter or return types
	
	// skipped method WrappedCredentialType.IndexOf with unsupported parameter or return types
	
	// skipped method WrappedCredentialType.IssuerIdentifier with unsupported parameter or return types
	
	// skipped method WrappedCredentialType.RandomBlindAttributeIndices with unsupported parameter or return types
	
	// skipped method WrappedCredentialType.RandomBlindAttributeNames with unsupported parameter or return types
	
	public native boolean revocationSupported();
	// skipped method WrappedCredentialType.SchemeManagerIdentifier with unsupported parameter or return types
	
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof WrappedCredentialType)) {
		    return false;
		}
		WrappedCredentialType that = (WrappedCredentialType)o;
		String thisLogo = getLogo();
		String thatLogo = that.getLogo();
		if (thisLogo == null) {
			if (thatLogo != null) {
			    return false;
			}
		} else if (!thisLogo.equals(thatLogo)) {
		    return false;
		}
		// skipped field WrappedCredentialType.CredentialType with unsupported type: github.com/AVecsi/pq-irmago.CredentialType
		
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {getLogo()});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("WrappedCredentialType").append("{");
		b.append("Logo:").append(getLogo()).append(",");
		return b.append("}").toString();
	}
}

