stages:
  - lint
  - test
  - build_bridge
  - build_app

variables:
  GOPATH: ${CI_PROJECT_DIR}/.cache
  GIT_SUBMODULE_STRATEGY: recursive
  PACKAGE_NAME: github.com/privacybydesign/irmamobile

image:
  name: privacybydesign/android_golang_gomobile_flutter:go1.18.3-flutter2.10.1

cache:
  paths:
    - .cache

lint:dart:
  script:
    - flutter format --line-length=120 --set-exit-if-changed lib/ test/ integration_test/
  stage: lint

test:flutter:
  script:
    - flutter test --no-sound-null-safety
  stage: test

build_bridge:
  stage: build_bridge
  interruptible: true
  only:
    - master
    - merge_requests
  artifacts:
    paths:
      - android/irmagobridge/irmagobridge.aar
  script:
    - gomobile bind -target android -o android/irmagobridge/irmagobridge.aar github.com/privacybydesign/irmamobile/irmagobridge

build_app:
  stage: build_app
  interruptible: true
  only:
    - master
    - merge_requests
  artifacts:
    paths:
      - build/app/outputs/apk/alpha/release/*.apk
  script:
    - flutter build apk --target-platform android-arm,android-arm64 --split-per-abi --flavor alpha

