stages:
  - lint
  - test
  - build_bridge
  - build_app

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PACKAGE_NAME: github.com/privacybydesign/irmamobile

image:
  name: privacybydesign/android_golang_dep_mobile_flutter:latest

before_script:
  - mkdir -p "$GOPATH/src/$(dirname "$PACKAGE_NAME")"
  - rm -f "$GOPATH/src/$PACKAGE_NAME"
  - ln -s "$CI_PROJECT_DIR" "$GOPATH/src/$PACKAGE_NAME"
  - cd "$GOPATH/src/$PACKAGE_NAME"

cache:
  paths:
    - vendor/

lint:dart:
  script:
    - flutter format --line-length=120 --set-exit-if-changed lib/ test/
  stage: lint

test:flutter:
  script:
    - flutter test
  stage: test

build_bridge:
  stage: build_bridge
  interruptible: true
  only: 
    - master
    - merge_requests
  artifacts:
    paths:
      - android/irmagobridge/irmagobridge.aar
  script:
    - dep ensure -v
    - gomobile bind -target android -o android/irmagobridge/irmagobridge.aar github.com/privacybydesign/irmamobile/irmagobridge
  
build_app:
  stage: build_app
  interruptible: true
  only: 
    - master
    - merge_requests
  artifacts:
    paths:
      - build/app/outputs/apk/release/*.apk
  script:
    - flutter build apk --target-platform android-arm,android-arm64 --split-per-abi

