name: irmamobile
description: IRMA Authentication
version: 6.2.3+136

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  sentry_flutter: ^6.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  flutter_svg: ^0.22.0
  flutter_i18n: ^0.30.0
  flutter_bloc: ^7.2.0
  equatable: ^2.0.3

  email_validator: ^2.0.1
  url_launcher: ^6.0.10
  json_annotation: ^4.0.1
  rxdart: ^0.27.2
  package_info: ^2.0.2
  collection: ^1.15.0
  qr_code_scanner: ^0.6.1
  font_awesome_flutter: ^9.1.0 # TODO remove once this package is no longer used
  share: ^2.0.4
  intl: ^0.17.0
  flutter_markdown: ^0.6.6
  shared_preferences: ^2.0.7
  async: ^2.6.1
  streaming_shared_preferences: ^2.0.0
  path_drawing: ^0.5.1
  flutter_jailbreak_detection: ^1.8.0
  visibility_detector: ^0.2.2
  quiver: ^3.0.1
  flutter_privacy_screen:
    # Remove link to fork when change is merged and released.
    # https://github.com/jeroentrappers/flutter_privacy_screen/pull/2
    git: https://github.com/ivard/flutter_privacy_screen.git

flutter_native_splash:
  image: assets/splash/startup.png
  color: "F2F5F8"
  android_disable_fullscreen: true

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  json_serializable: ^4.1.4
  lint: ^1.6.0
  flutter_native_splash: ^1.2.1
  build_runner: ^2.1.2


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/locales/
    - assets/enrollment/
    - assets/history/
    - assets/wallet/
    - assets/generic/
    - assets/error/
    - assets/help/
    - assets/reset/
    - assets/non-free/
    - assets/disclosure/
    - assets/splash/
    - assets/rooted_warning/
  fonts:
    - family: Karla
      fonts:
        - asset: fonts/karla/Karla-Regular.ttf
        - asset: fonts/karla/Karla-RegularItalic.ttf
          style: italic
        - asset: fonts/karla/Karla-Bold.ttf
          weight: 700
        - asset: fonts/karla/Karla-BoldItalic.ttf
          style: italic
          weight: 700
    - family: Montserrat
      fonts:
        - asset: fonts/montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/montserrat/Montserrat-RegularItalic.ttf
          weight: 400
          style: italic
        - asset: fonts/montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/montserrat/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/montserrat/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/montserrat/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
    - family: Ubuntu
      fonts:
        - asset: fonts/ubuntu/Ubuntu-Regular.ttf
          weight: 400
          style: italic
        - asset: fonts/ubuntu/Ubuntu-Medium.ttf
          weight: 500
        - asset: fonts/ubuntu/Ubuntu-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/ubuntu/Ubuntu-Bold.ttf
          weight: 700
        - asset: fonts/ubuntu/Ubuntu-BoldItalic.ttf
          weight: 700
          style: italic
    - family: Roboto
      fonts:
        - asset: fonts/roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/roboto/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/roboto/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
    - family: IrmaIcons
      fonts:
        - asset: fonts/irma-icons/IrmaIcons.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
