name: Delivery

on:
  push:
    branches: [ master ]

jobs:
  # We make sure that lint succeeds before we start any other job to
  # prevent that the setup-build-environment action runs in parallel.
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Setup build environment
        uses: ./.github/actions/setup-build-environment
      - run: bundle exec fastlane lint
  unit-test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Setup build environment
        uses: ./.github/actions/setup-build-environment
      - run: bundle exec fastlane unit_test
  build-irmagobridge-ios:
    runs-on: macos-12
    needs: lint
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Setup build environment
        uses: ./.github/actions/setup-build-environment
      - run: bundle exec fastlane ios_build_irmagobridge
      - uses: actions/upload-artifact@v3
        with:
          name: irmagobridge-ios
          path: ios/Runner/Irmagobridge.xcframework/
  build-irmagobridge-android:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Setup build environment
        uses: ./.github/actions/setup-build-environment
      - run: bundle exec fastlane android_build_irmagobridge
      - uses: actions/upload-artifact@v3
        with:
          name: irmagobridge-android
          path: android/irmagobridge/irmagobridge.aar
  build-app-ios-alpha:
    # Ad Hoc builds do not require unique build numbers, so we can build this on every push.
    runs-on: macos-12
    needs:
      - unit-test
      - build-irmagobridge-ios
    environment: ad-hoc-alpha
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup build environment
        uses: ./.github/actions/setup-build-environment
      - name: Download app artifact
        uses: actions/download-artifact@v3
        with:
          name: irmagobridge-ios
          path: ios/Runner/Irmagobridge.xcframework/
      - name: Decode binary environment secrets
        env:
          APPLE_DISTRIBUTION_CERTIFICATE: ${{ secrets.APPLE_DISTRIBUTION_CERTIFICATE }}
          APPLE_PROVISIONING_PROFILE: ${{ secrets.APPLE_PROVISIONING_PROFILE }}
        run: |
          mkdir -p ./fastlane/profiles
          echo $APPLE_DISTRIBUTION_CERTIFICATE | base64 --decode > ./fastlane/profiles/apple_distribution.p12
          echo $APPLE_PROVISIONING_PROFILE | base64 --decode > ./fastlane/profiles/ad_hoc_alpha.mobileprovision
      - run: >
          bundle exec fastlane ios_build_app
          flavor:alpha
          certificate_path:profiles/apple_distribution.p12
          certificate_password:${{ secrets.APPLE_DISTRIBUTION_CERTIFICATE_PASSWORD }}
          provisioning_profile_path:profiles/ad_hoc_alpha.mobileprovision
          sentry_dsn:${{ secrets.SENTRY_DSN }}
      - uses: actions/upload-artifact@v3
        with:
          name: app-alpha-ios
          path: ./fastlane/build/*.ipa
  build-app-android-alpha:
    # The Android builds are only signed with a development key. Signing needs to be done manually still.
    runs-on: ubuntu-latest
    needs:
      - unit-test
      - build-irmagobridge-android
    environment: ad-hoc-alpha
    strategy:
      matrix:
        target-platform: [ android-arm, android-arm64, android-x64 ]
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup build environment
        uses: ./.github/actions/setup-build-environment
      - name: Download irmagobridge artifact
        uses: actions/download-artifact@v3
        with:
          name: irmagobridge-android
          path: android/irmagobridge/
      - run: >
          bundle exec fastlane android_build_app
          flavor:alpha
          target_platform:${{ matrix.target-platform }}
          sentry_dsn:${{ secrets.SENTRY_DSN }}
      - uses: actions/upload-artifact@v3
        with:
          name: app-alpha-${{ matrix.target-platform }}
          path: ./fastlane/build/*.apk
  bundle-app-alpha:
    runs-on: ubuntu-latest
    needs:
     - build-app-ios-alpha
     - build-app-android-alpha
    steps:
      - name: Download app-alpha-ios artifact
        uses: actions/download-artifact@v3
        with:
          name: app-alpha-ios
      - name: Download app-alpha-android-arm artifact
        uses: actions/download-artifact@v3
        with:
          name: app-alpha-android-arm
      - name: Download app-alpha-android-arm64 artifact
        uses: actions/download-artifact@v3
        with:
          name: app-alpha-android-arm64
      - name: Download app-alpha-android-x64 artifact
        uses: actions/download-artifact@v3
        with:
          name: app-alpha-android-x64
      - name: Bundle all artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-bundle-alpha
          path: .
