# Workflow to check whether changes to master fulfill all requirements.
# We execute build stages in separate jobs to prevent artifact duplication.
name: Status checks

on:
  push:
    branches: [ master ]
  pull_request:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  # We make sure that lint succeeds before we start any other job to
  # prevent that the setup-build-environment action runs in parallel.
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Setup build environment
        uses: ./.github/actions/setup-build-environment
      - run: bundle exec fastlane lint
  unit-test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Setup build environment
        uses: ./.github/actions/setup-build-environment
      - run: bundle exec fastlane unit_test
  build-irmagobridge-ios:
    runs-on: macos-latest
    needs: lint
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Setup build environment
        uses: ./.github/actions/setup-build-environment
      - run: bundle exec fastlane ios_build_irmagobridge
      - uses: actions/upload-artifact@v3
        with:
          name: irmagobridge-ios
          path: ios/Runner/Irmagobridge.xcframework/
  build-irmagobridge-android:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Setup build environment
        uses: ./.github/actions/setup-build-environment
      - run: bundle exec fastlane android_build_irmagobridge
      - uses: actions/upload-artifact@v3
        with:
          name: irmagobridge-android
          path: android/irmagobridge/irmagobridge.aar
  build-app-ios:
    runs-on: macos-latest
    needs: build-irmagobridge-ios
    strategy:
      matrix:
        flavor: [ alpha, beta ]
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup build environment
        uses: ./.github/actions/setup-build-environment
      - name: Download irmagobridge artifact
        uses: actions/download-artifact@v3
        with:
          name: irmagobridge-ios
          path: ios/Runner/Irmagobridge.xcframework/
      - run: bundle exec fastlane ios_build_app flavor:${{ matrix.flavor }}
      # We don't run ios_export here, so we have no artifact to upload for now.
  build-app-android:
    runs-on: ubuntu-latest
    needs: build-irmagobridge-android
    strategy:
      matrix:
        flavor: [ alpha, beta ]
        target-platform: [ android-arm, android-arm64, android-x64 ]
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup build environment
        uses: ./.github/actions/setup-build-environment
      - name: Download irmagobridge artifact
        uses: actions/download-artifact@v3
        with:
          name: irmagobridge-android
          path: android/irmagobridge/irmagobridge.aar
      - run: bundle exec fastlane android_build_app flavor:${{ matrix.flavor }} target_platform:${{ matrix.target-platform }}
      - uses: actions/upload-artifact@v3
        with:
          name: build-app-${{ matrix.flavor }}-${{ matrix.target-platform }}
          path: ./fastlane/build/*.apk
