# Workflow to check whether changes to master fulfill all requirements.
name: Status checks

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup build environment
        uses: ./.github/actions/setup-build-environment
      - name: Check flutter format
        run: flutter format --line-length=120 --set-exit-if-changed lib/ test/ integration_test/
      - name: Check flutter analyze for errors
        run: flutter analyze --no-fatal-infos --no-fatal-warnings lib/ test/ integration_test/

